collections:
  - name: "laudos"
    label: "┗ Modelos de Laudo"
    folder: "src/laudos"
    create: true
    slug: "{{categoria}}-{{title}}"
    fields:
      - {label: "Categoria", name: "categoria", widget: "select", options: ["Urg锚ncia-Neuro", "Urg锚ncia-T贸rax", "Abdome-F铆gado", "T贸rax", "AngioTC", "Pelve Feminina", "Pr贸stata"]}
      - {label: "Subt贸pico", name: "subtopico", widget: "text", default: ""}
      - {label: "Frase Laudo", name: "frase", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
